name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Ubah jika branch utama kamu 'master'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-southeast2 # Ganti sesuai region kamu (misal: asia-southeast2 untuk Jakarta)
  SERVICE_NAME: nyam-ml-api
  GCS_BUCKET: nyam-models-prod # GANTI INI
  FOOD_MODEL: modelML_foodRecognition.keras
  BMR_MODEL: modelML_bmiRate.keras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup GCloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Configure Docker for Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker

      # Build and Push Docker Image
      - name: Build and Push
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars: |
            GCS_BUCKET_NAME=${{ env.GCS_BUCKET }}
            FOOD_MODEL_BLOB_NAME=${{ env.FOOD_MODEL }}
            BMR_MODEL_BLOB_NAME=${{ env.BMR_MODEL }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            TF_ENABLE_ONEDNN_OPTS=0
          flags: "--memory=2Gi --cpu=1" # TensorFlow butuh RAM lumayan
