name: Deploy ML API Hybrid

on:
  push:
    branches:
      - main # Atau 'master', sesuaikan branch kamu

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast2 # Jakarta (Pastikan repo dibuat di sini)
  REPO_NAME: nyam-repo # Nama Artifact Registry
  SERVICE_NAME: nyam-ml-api # Nama Service Cloud Run

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}" # Pastikan nama secret ini benar

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Build & Push ke Artifact Registry
      - name: Build and Push
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # Deploy ke Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          # CPU & Memory diset agak longgar untuk TensorFlow + Image Processing
          flags: "--allow-unauthenticated --memory=2Gi --cpu=1"

          # --- BAGIAN PENTING (UPDATE DISINI) ---
          env_vars: |
            GCS_BUCKET_NAME=nyam-models-prod
            FOOD_MODEL_BLOB_NAME=modelML_foodRecognition.keras
            BMR_MODEL_BLOB_NAME=modelML_bmiRate.keras
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            TF_ENABLE_ONEDNN_OPTS=0
